# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codigos', '0005_auto_20170525_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefono', models.CharField(max_length=10)),
                ('codigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='codigos.Codigo')),
            ],
        ),
    ]
