# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20170525_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['fecha']},
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='creacion',
            new_name='fecha',
        ),
    ]
