# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='telefono',
            new_name='teléfono',
        ),
    ]
