# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20170606_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='código',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
