# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20190624_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='status_sms',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
