# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_venta_status_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='status_sms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
