# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('duracion', models.IntegerField()),
                ('unidad_duracion', models.IntegerField(choices=[(1, 'Horas'), (2, 'Dias')])),
            ],
        ),
    ]
