# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='unidad_duracion',
            field=models.IntegerField(choices=[(1, 'Hora(s)'), (2, 'Dia(s)'), (3, 'Semana(s)'), (4, 'Mese(s)'), (5, 'Año(s)')]),
        ),
    ]
