# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0002_auto_20170525_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
