# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0003_auto_20170525_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
