# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0004_codigo_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'ordering': ['unidad_duracion', 'duracion', 'creacion']},
        ),
    ]
