# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0005_auto_20170525_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Hora(s)'), (2, 'Dia(s)'), (3, 'Semana(s)'), (4, 'Mese(s)'), (5, 'Año(s)')], default=0),
        ),
    ]
