# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0006_codigo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'vendido')], default=0),
        ),
    ]
