# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0007_auto_20170525_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('unidad_duracion', models.IntegerField(choices=[(1, 'Hora(s)'), (2, 'Dia(s)'), (3, 'Semana(s)'), (4, 'Mese(s)'), (5, 'Año(s)')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='codigo',
            options={},
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='unidad_duracion',
        ),
    ]
