# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0008_auto_20170525_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigo',
            name='duracion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codigos.Duracion'),
        ),
    ]
