# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0009_codigo_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField()),
                ('unidad_duracion', models.IntegerField(choices=[(1, 'Hora(s)'), (2, 'Dia(s)'), (3, 'Semana(s)'), (4, 'Mese(s)'), (5, 'Año(s)')])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['unidad_duracion', 'duracion'],
            },
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='codigo',
            name='precio',
        ),
        migrations.DeleteModel(
            name='Duracion',
        ),
        migrations.AddField(
            model_name='codigo',
            name='caracteristicas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codigos.Caracteristicas'),
        ),
    ]
