# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0012_auto_20170525_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
