# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0013_auto_20170525_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50), max_length=40),
        ),
    ]
