# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0014_plan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
