# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0015_auto_20170529_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'Vendido')], default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
