# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0016_auto_20170530_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'ordering': ['creacion']},
        ),
        migrations.AddField(
            model_name='plan',
            name='codigos_disponibles',
            field=models.IntegerField(default=0),
        ),
    ]
