# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0017_auto_20170606_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.RenameField(
            model_name='codigo',
            old_name='creacion',
            new_name='creación',
        ),
        migrations.RenameField(
            model_name='codigo',
            old_name='codigo',
            new_name='código',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='codigos_disponibles',
            new_name='códigos_disponibles',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='duracion',
            new_name='duración',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='unidad_duracion',
            new_name='unidad_duración',
        ),
    ]
