# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0019_auto_20170606_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'ordering': ['creación']},
        ),
    ]
