# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0020_auto_20170606_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigo',
            options={'ordering': ['creacion']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['unidad_duracion', 'duracion']},
        ),
        migrations.RenameField(
            model_name='codigo',
            old_name='código',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='codigo',
            old_name='creación',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='códigos_disponibles',
            new_name='codigos_disponibles',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='duración',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='unidad_duración',
            new_name='unidad_duracion',
        ),
    ]
