# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0022_auto_20170606_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duracion',
            field=models.IntegerField(verbose_name='What song are you going to sing?'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unidad_duracion',
            field=models.IntegerField(choices=[(1, 'Hora(s)'), (2, 'Dia(s)'), (3, 'Semana(s)'), (4, 'Mese(s)'), (5, 'Año(s)')]),
        ),
    ]
