# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170828_1341'),
        ('codigos', '0024_auto_20170606_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Negocio'),
        ),
    ]
