# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 03:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0025_plan_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
