# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190624_2043'),
        ('codigos', '0026_auto_20171208_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['punto_venta', 'unidad_duracion', 'duracion']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='negocio',
        ),
        migrations.AddField(
            model_name='plan',
            name='punto_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.PuntoDeVenta'),
        ),
        migrations.AlterField(
            model_name='codigo',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], default='Vendido', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unidad_duracion',
            field=models.IntegerField(choices=[('H', 'Hora(s)'), ('D', 'Dia(s)'), ('S', 'Semana(s)'), ('M', 'Mese(s)'), ('A', 'Año(s)')], verbose_name='Unidad de tiempo'),
        ),
    ]
