# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-25 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0027_auto_20190624_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PuntoDeVenta'),
        ),
    ]
