# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0028_auto_20190624_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='unidad_duracion',
            field=models.CharField(choices=[('H', 'Hora(s)'), ('D', 'Dia(s)'), ('S', 'Semana(s)'), ('M', 'Mese(s)'), ('A', 'Año(s)')], max_length=1, verbose_name='Unidad de tiempo'),
        ),
    ]
