# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0029_auto_20190626_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unidad_duracion',
            field=models.CharField(choices=[('H', 'Hora'), ('D', 'Dia'), ('S', 'Semana'), ('M', 'Mes'), ('A', 'Año')], max_length=1, verbose_name='Unidad de tiempo'),
        ),
    ]
