# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0030_auto_20190626_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterField(
            model_name='codigo',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido')], default='Disponible', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True),
        ),
    ]
