# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0031_auto_20190626_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='unidad_duracion',
            field=models.CharField(choices=[('Hora(s)', 'Hora(s)'), ('Dia(s)', 'Dia(s)'), ('Semana(s)', 'Semana(s)'), ('Mes(s)', 'Mes(s)'), ('Año(s)', 'Año(s)')], max_length=10, verbose_name='Unidad de tiempo'),
        ),
    ]
