# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0032_auto_20190626_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='unidad_duracion',
            field=models.CharField(choices=[('h', 'Hora(s)'), ('d', 'Dia(s)')], max_length=1, verbose_name='Unidad de tiempo'),
        ),
    ]
