# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0033_auto_20190701_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codigos.Plan')),
            ],
        ),
    ]
