# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-01 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0034_recarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recarga',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
