# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-01 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codigos', '0035_auto_20190801_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
