# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-01 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0036_recarga_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recarga',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
