# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0037_auto_20190801_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(max_length=11),
        ),
    ]
