# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, choices=[('Dueño', 'Dueño'), ('Empleado', 'Empleado')], max_length=10, null=True),
        ),
    ]
