# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigos', '0026_auto_20171208_2154'),
        ('accounts', '0002_auto_20170828_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tienda',
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='domicilio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('Hidalgo', 'Hidalgo')], default='Hidalgo', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='municipio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Negocio',
        ),
    ]
