# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171208_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
