# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-25 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_perfil_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.TextField()),
                ('codigo_postal', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Hidalgo', 'Hidalgo')], default='Hidalgo', max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
