# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-25 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190624_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeventa',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
