# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190624_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntodeventa',
            options={'verbose_name_plural': 'Puntos de venta'},
        ),
        migrations.AlterField(
            model_name='puntodeventa',
            name='estado',
            field=models.CharField(choices=[('Hidalgo', 'Hidalgo'), ('Querétaro', 'Querétaro')], default='Hidalgo', max_length=30),
        ),
    ]
