# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190626_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='wifi',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
