# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_puntodeventa_wifi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntodeventa',
            old_name='wifi',
            new_name='nombre_red',
        ),
    ]
