# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-06-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190626_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeventa',
            name='nombre_red',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
