# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_puntodeventa_codigos_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
