# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_puntodeventa_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodeventa',
            name='slug',
        ),
    ]
