# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-07-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_puntodeventa_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeventa',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del punto de venta'),
        ),
    ]
