# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-01 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190701_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='saldo_acumulado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
