# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_puntodeventa_saldo_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='porcentaje_comision',
            field=models.IntegerField(default=10),
        ),
    ]
