# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-08-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_puntodeventa_tecnologia_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeventa',
            name='porcentaje_comision',
            field=models.IntegerField(default=20),
        ),
    ]
