# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-04 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_antena'),
    ]

    operations = [
        migrations.AddField(
            model_name='antena',
            name='ssid',
            field=models.CharField(default='Mi red', max_length=50, verbose_name='SSID o nombre de la red'),
        ),
        migrations.AlterField(
            model_name='antena',
            name='ip',
            field=models.TextField(verbose_name='IP o DNS'),
        ),
        migrations.AlterField(
            model_name='antena',
            name='tecnologia',
            field=models.CharField(choices=[('Unifi', 'Unifi'), ('Mikrotik', 'Mikrotik')], max_length=10, verbose_name='Tecnología'),
        ),
    ]
