# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-04 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190904_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodeventa',
            name='nombre_red',
        ),
        migrations.RemoveField(
            model_name='puntodeventa',
            name='tecnologia_wifi',
        ),
    ]
