# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-09-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190904_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antena',
            name='ip',
            field=models.TextField(blank=True, null=True, verbose_name='IP o DNS'),
        ),
        migrations.AlterField(
            model_name='antena',
            name='password',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='antena',
            name='usuario',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
